export const commonCodeList = [
    { grpCd: '00', grpNm: 'User position', cd: '00', cdNm: 'Position' },
    { grpCd: '00', grpNm: 'User position', cd: '01', cdNm: 'Executive advisor' },
    { grpCd: '00', grpNm: 'User position', cd: '02', cdNm: 'General manager' },
    { grpCd: '00', grpNm: 'User position', cd: '03', cdNm: 'Chief' },
    { grpCd: '00', grpNm: 'User position', cd: '04', cdNm: 'Assistant manager' },
    { grpCd: '00', grpNm: 'User position', cd: '05', cdNm: 'Staff' },
    { grpCd: '01', grpNm: 'User authorization', cd: '01', cdNm: 'Normal' },
    { grpCd: '01', grpNm: 'User authorization', cd: '02', cdNm: 'Admin' },
    { grpCd: '01', grpNm: 'User authorization', cd: '03', cdNm: 'Developer' },
    { grpCd: '02', grpNm: 'Cassete state', cd: '0', cdNm: 'Empty' },
    { grpCd: '02', grpNm: 'Cassete state', cd: '1', cdNm: 'Ready' },
    { grpCd: '02', grpNm: 'Cassete state', cd: '2', cdNm: 'Analyzing' },
    { grpCd: '02', grpNm: 'Cassete state', cd: '3', cdNm: 'Complete' },
    { grpCd: '02', grpNm: 'Cassete state', cd: '4', cdNm: 'Error' },
    { grpCd: '02', grpNm: 'Cassete state', cd: '9', cdNm: 'Scan' },
    { grpCd: '03', grpNm: 'Processing code', cd: '01', cdNm: 'Cassette Loaded.'},
    { grpCd: '03', grpNm: 'Processing code', cd: '02', cdNm: 'PB/BM Sequence Start.'},
    { grpCd: '03', grpNm: 'Processing code', cd: '03', cdNm: 'Cassette Scanning......'},
    { grpCd: '03', grpNm: 'Processing code', cd: '04', cdNm: 'Cassette Scanned.'},
    { grpCd: '03', grpNm: 'Processing code', cd: '05', cdNm: 'Loading Slide #'},
    { grpCd: '03', grpNm: 'Processing code', cd: '06', cdNm: 'Barcode Scanned : '},
    { grpCd: '03', grpNm: 'Processing code', cd: '07', cdNm: 'Low Power Slide Scanning......'},
    { grpCd: '03', grpNm: 'Processing code', cd: '08', cdNm: 'Low Power Slide Scan Complete.'},
    { grpCd: '03', grpNm: 'Processing code', cd: '09', cdNm: 'Dispensing Immersion Oil......'},
    { grpCd: '03', grpNm: 'Processing code', cd: '10', cdNm: 'High Power Slide Scanning......'},
    { grpCd: '03', grpNm: 'Processing code', cd: '11', cdNm: 'RBC Classification Processing......'},
    { grpCd: '03', grpNm: 'Processing code', cd: '11', cdNm: 'WBC Classification Processing......'},
    { grpCd: '03', grpNm: 'Processing code', cd: '12', cdNm: 'Unloading Slide #'},
    { grpCd: '03', grpNm: 'Processing code', cd: '13', cdNm: 'Cassette Complete'},
    { grpCd: '04', grpNm: 'Analysis type', cd: '01', cdNm: 'PB smear'},
    { grpCd: '04', grpNm: 'Analysis type', cd: '02', cdNm: 'BM smear'},
    { grpCd: '04', grpNm: 'Analysis type', cd: '03', cdNm: 'Touch print'},
    { grpCd: '04', grpNm: 'Analysis type', cd: '04', cdNm: 'BM biopsy'},
    { grpCd: '04', grpNm: 'Analysis type', cd: '05', cdNm: 'Clot section'},
    { grpCd: '05', grpNm: 'Cell count', cd: '01', cdNm: '100 count'},
    { grpCd: '05', grpNm: 'Cell count', cd: '02', cdNm: '200 count'},
    { grpCd: '05', grpNm: 'Cell count', cd: '03', cdNm: '300 count'},
    { grpCd: '05', grpNm: 'Cell count', cd: '04', cdNm: '400 count'},
    { grpCd: '05', grpNm: 'Cell count', cd: '05', cdNm: '500 count'},
    { grpCd: '06', grpNm: 'General stain', cd: '01', cdNm: 'Wright stain'},
    { grpCd: '06', grpNm: 'General stain', cd: '02', cdNm: 'Giemsa stain'},
    { grpCd: '06', grpNm: 'General stain', cd: '03', cdNm: 'Wright & Giemsa stain'},
    { grpCd: '07', grpNm: 'Special stain', cd: '04', cdNm: 'Iron stain'},
    { grpCd: '07', grpNm: 'Special stain', cd: '05', cdNm: 'Trichrome stain'},
    { grpCd: '07', grpNm: 'Special stain', cd: '06', cdNm: 'Myeloperoxidase stain'},
    { grpCd: '07', grpNm: 'Special stain', cd: '07', cdNm: 'NSE stain'},
    { grpCd: '07', grpNm: 'Special stain', cd: '08', cdNm: 'NSE stain after NaFinhibition'},
    { grpCd: '07', grpNm: 'Special stain', cd: '09', cdNm: 'Reticulin stain'},
    { grpCd: '07', grpNm: 'Special stain', cd: '10', cdNm: 'PAS stain'},
    { grpCd: '08', grpNm: 'Immuno stain', cd: '11', cdNm: 'CD 3'},
    { grpCd: '08', grpNm: 'Immuno stain', cd: '12', cdNm: 'CD 5'},
    { grpCd: '08', grpNm: 'Immuno stain', cd: '13', cdNm: 'CD 20'},
    { grpCd: '08', grpNm: 'Immuno stain', cd: '14', cdNm: 'CD 79a'},
    { grpCd: '09', grpNm: 'Sampling stain', cd: '01', cdNm: 'Single'},
    { grpCd: '09', grpNm: 'Sampling stain', cd: '02', cdNm: 'Both'},
    { grpCd: '10', grpNm: 'Gender', cd: '01', cdNm: 'Male'},
    { grpCd: '10', grpNm: 'Gender', cd: '02', cdNm: 'Female'},
    { grpCd: '11', grpNm: 'Test Type', cd: '01', cdNm: 'PB'},
    { grpCd: '11', grpNm: 'Test Type', cd: '02', cdNm: 'BF(Default)'},
    { grpCd: '11', grpNm: 'Test Type', cd: '03', cdNm: 'BF(Select)'},
    { grpCd: '11', grpNm: 'Test Type', cd: '04', cdNm: 'Premium'},
    { grpCd: '12', grpNm: 'Signed state', cd: '01', cdNm: 'Signed'},
    { grpCd: '12', grpNm: 'Signed state', cd: '02', cdNm: 'Ready'},
    { grpCd: '13', grpNm: 'Log type', cd: '00', cdNm: 'User log'},
    { grpCd: '13', grpNm: 'Log type', cd: '01', cdNm: 'System log'},
    { grpCd: '14', grpNm: 'Slot state', cd: '00', cdNm: 'Empty'},
    { grpCd: '14', grpNm: 'Slot state', cd: '01', cdNm: 'Ready'},
    { grpCd: '14', grpNm: 'Slot state', cd: '02', cdNm: 'Scan'},
    { grpCd: '14', grpNm: 'Slot state', cd: '03', cdNm: 'Analyzing'},
    { grpCd: '14', grpNm: 'Slot state', cd: '04', cdNm: 'Complete'},
    { grpCd: '14', grpNm: 'Slot state', cd: '05', cdNm: 'Error'}
]